"""Export local wardrobe data to migrations/002_seed_data.sql.

Run this once locally whenever you want to update the seed data:
    python scripts/export_seed.py

Generates SQL INSERT statements for wardrobe items (with images as hex bytea)
and their chunk embeddings. Commit the result and Railway runs it on deploy.
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from db.postgres import get_conn

OUT = Path(__file__).parent.parent / "migrations" / "002_seed_data.sql"


def export():
    with get_conn() as conn:
        items = conn.execute("""
            SELECT id, item_name, category, subcategory, color, pattern, season,
                   comfort, style_tags, suited_for, source_file, description,
                   fabric, weather_suitability, style_vibe, occasion_context,
                   photo_scene, place_type, place_name, place_activity, place_vibe,
                   semantic_text, image_data, image_mime, source_photo,
                   embedded_at, chunk_id
            FROM wardrobe ORDER BY id
        """).fetchall()

        chunks = conn.execute("""
            SELECT id, content, embedding::text as embedding,
                   source, conversation_id, title,
                   timestamp, msg_timestamp, role, type,
                   pillar, dimension, classified,
                   cluster_id, cluster_label, extra
            FROM chunks
            WHERE conversation_id LIKE 'wardrobe_item_%'
               OR type = 'wardrobe_item'
        """).fetchall()

    lines = [
        "-- Auto-generated wardrobe seed data",
        "-- Generated by scripts/export_seed.py",
        "-- Do not edit manually\n",
        "-- Reset sequence so IDs don't collide",
        "DELETE FROM outfit_history;",
        "DELETE FROM chunks WHERE conversation_id LIKE 'wardrobe_item_%' OR type = 'wardrobe_item';",
        "DELETE FROM wardrobe;\n",
    ]

    print(f"Exporting {len(items)} wardrobe items...")
    for r in items:
        img_hex = ("'\\x" + bytes(r["image_data"]).hex() + "'::bytea") if r["image_data"] else "NULL"
        style_tags = r["style_tags"] if isinstance(r["style_tags"], str) else json.dumps(r["style_tags"])

        def q(v):
            if v is None:
                return "NULL"
            s = str(v).replace("'", "''")
            return f"'{s}'"

        lines.append(
            f"INSERT INTO wardrobe (id, item_name, category, subcategory, color, pattern, season, "
            f"comfort, style_tags, suited_for, source_file, description, "
            f"fabric, weather_suitability, style_vibe, occasion_context, "
            f"photo_scene, place_type, place_name, place_activity, place_vibe, "
            f"semantic_text, image_data, image_mime, source_photo, chunk_id) VALUES ("
            f"{r['id']}, {q(r['item_name'])}, {q(r['category'])}, {q(r['subcategory'])}, "
            f"{q(r['color'])}, {q(r['pattern'])}, {q(r['season'])}, {q(r['comfort'])}, "
            f"'{style_tags}'::jsonb, {q(r['suited_for'])}, {q(r['source_file'])}, "
            f"{q(r['description'])}, {q(r['fabric'])}, {q(r['weather_suitability'])}, "
            f"{q(r['style_vibe'])}, {q(r['occasion_context'])}, {q(r['photo_scene'])}, "
            f"{q(r['place_type'])}, {q(r['place_name'])}, {q(r['place_activity'])}, "
            f"{q(r['place_vibe'])}, {q(r['semantic_text'])}, "
            f"{img_hex}, {q(r['image_mime'])}, {q(r['source_photo'])}, {q(r['chunk_id'])}"
            f") ON CONFLICT (id) DO NOTHING;"
        )

    lines.append(f"\nSELECT setval('wardrobe_id_seq', (SELECT MAX(id) FROM wardrobe));")

    print(f"Exporting {len(chunks)} wardrobe chunks...")
    if chunks:
        lines.append("")
        for c in chunks:
            raw_emb = c["embedding"]
            emb_sql = f"'{raw_emb}'::vector" if raw_emb else "NULL"
            extra = c["extra"] if isinstance(c["extra"], str) else json.dumps(c["extra"] or {})

            def q(v):
                if v is None:
                    return "NULL"
                s = str(v).replace("'", "''")
                return f"'{s}'"

            ts_sql = "NULL" if not c["timestamp"] else q(str(c["timestamp"]))
            msg_ts_sql = "NULL" if not c["msg_timestamp"] else q(str(c["msg_timestamp"]))

            lines.append(
                f"INSERT INTO chunks (id, content, embedding, source, conversation_id, title, "
                f"timestamp, msg_timestamp, role, type, pillar, dimension, classified, "
                f"cluster_id, cluster_label, extra) VALUES ("
                f"{q(c['id'])}, {q(c['content'])}, "
                f"{emb_sql}, "
                f"{q(c['source'])}, {q(c['conversation_id'])}, {q(c['title'])}, "
                f"{ts_sql}, {msg_ts_sql}, "
                f"{q(c['role'])}, {q(c['type'])}, {q(c['pillar'])}, {q(c['dimension'])}, "
                f"{str(c['classified']).upper()}, "
                f"{q(c['cluster_id'])}, {q(c['cluster_label'])}, '{extra}'::jsonb"
                f") ON CONFLICT (id) DO NOTHING;"
            )

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    size_kb = OUT.stat().st_size // 1024
    print(f"Written to {OUT} ({size_kb} KB)")
    print(f"  {len(items)} wardrobe items")
    print(f"  {len(chunks)} chunks")


if __name__ == "__main__":
    export()
